version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      time: "09:32"
      timezone: "GMT"
   
    ignore:
      - dependency-name: "lodash"
        # For Lodash, ignore all updates
    # Disable version updates for npm dependencies
    open-pull-requests-limit: 1
